baseURL = 'https://sezaki02.github.io/Phalacrocoracidae/'
languageCode = 'ja'
title = 'Sticky was half-cut.'
publishDir = "docs"
canonifyurls = true
theme = 'holy'


[menu]
 [[menu.main]]
    name = "About"
    pageRef = "/about"
    weight = 10
